### ISSUE TITLE
Sort the WSGI and ENVIRON Variables in the E-Mail Report

### ISSUE THREAD

**Issue by href** [TurboGears/backlash#10]
It would be nice if the WSGI and ENVIRON Variables in the E-Mail Report would be sorted by key. Currently the order is random because those values are stored in a dictionary.

This would make it easier to find out what's going on at a glance.

**Comment by amol-** [comment]
should be solved by https://github.com/TurboGears/backlash/commit/2265fd1a5a335ce5356f591eb6ef319503d7daf2 released as part of 0.1.1

**Comment by href** [comment]
Awesome, thanks!
