### ISSUE TITLE
Add the ability to define the smtp port.

### ISSUE THREAD

**Issue by href** [TurboGears/backlash#7]
I'm trying out backlash for a new server deployment and I noticed that it's not possible to define an smtp port to the EmailReporter. Adding this option would be nice, as it allows for non-standard smtp ports when using a non-privileged smtp testserver for example.

**Comment by amol-** [comment]
This should be already available as backlash uses `smtplib.SMTP` which uses `connect()` which states

```
If the hostname ends with a colon (':') followed by a number, 
that suffix will be stripped off and the number interpreted
as the port number to use.
```

Isn't it working for you?

**Comment by href** [comment]
It is actually, I totally missed this in the docs. I tested it and it works!

Thanks and sorry for the unnecessary ticket :sweat:
